version: '3.5'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: nc
      POSTGRES_PASSWORD:
    volumes:
      - target: /var/lib/postgresql/data
        source: ./mounts/db
        type: bind
    networks: [ local ]
  cache:
    image: redis:alpine
    networks: [ local ]
  app:
    image: nextcloud:stable-apache
    volumes:
      - type: bind
        source: ./mounts/data
        target: /var/www/html
      - type: bind
        source: /home/scott/Music
        target: /var/www/html/data/scott/Music
      - type: bind
        source: /home/scott/Music
        target: /var/www/html/data/owen/Music
    networks: [ web, local ]
    environment:
      POSTGRES_DB: nc
      POSTGRES_USER: nc
      POSTGRES_PASSWORD:
      POSTGRES_HOST: database
      REDIS_HOST: cache
    labels:
      traefik.docker.network: web
      traefik.domain: tams.tech
      traefik.enable: 'true'
      traefik.frontend.rule: Host:cloud.tams.tech,nc.tams.tech

networks:
  web:
    external: true
  local:
    internal: true
